syntax on
filetype plugin on

set noerrorbells
set tabstop=4 
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set backspace=indent,eol,start
set nu
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set encoding=utf-8
set fileformat=unix
set clipboard=unnamed
set mouse+=a
set relativenumber
" Provides tab-completion for all file related tasks
" - Hit tab to find:
set path+=**
set wildmenu

" For gruvbox
set termguicolors

" For coc.nvim
set hidden
set updatetime=300
set shortmess+=c
set signcolumn=yes

" set colorcolumn=80
" highlight ColorColumn ctermbg=235 guibg=lightgrey

" autocmd BufRead,BufNewFile *.c,*.h setlocal tabstop=2 shiftwidth=2 softtabstop=2

call plug#begin('~/.vim/plugged')

" Make sure you use single quotes
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'morhetz/gruvbox'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'
Plug 'majutsushi/tagbar'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" NERDTree auto open
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>

" gruvbox theme settings
let g:gruvbox_contrast_dark = 'hard'
autocmd vimenter * colorscheme gruvbox

" powerline settings
let g:airline_powerline_fonts = 1

" TagBar Settings
map <C-t> :TagbarToggle<CR>

" coc.vim Settings
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
